import{Base}from'./base.js';import{rect,letterPage,asset,W,H}from'../render.js';
export class Dark extends Base {constructor(e,ch){super(e,ch,2);this.map=e.config.maze;this.p={x:.08+1.5*.06,y:.22+1.5*.073,vy:0};this.pages=e.config.pageCells.map(([x,y],k)=>({x:.08+(x+.5)*.06,y:.22+(y+.5)*.073,k}));this.bots=[this.bot(13,3),this.bot(7,7)];this.got=0;this.still=0;this.face=0;this.aiTime=0}
 bot(x,y){return{x:.08+(x+.5)*.06,y:.22+(y+.5)*.073,target:null}}
 cell(x,y){return{x:Math.floor((x-.08)/.06),y:Math.floor((y-.22)/.073)}}
 free(x,y){const q=this.cell(x,y);return this.map[q.y]?.[q.x]==='0'}
 move(p,dx,dy){const r=.009;if(this.free(p.x+dx-r,p.y-r)&&this.free(p.x+dx+r,p.y+r))p.x+=dx;if(this.free(p.x-r,p.y+dy-r)&&this.free(p.x+r,p.y+dy+r))p.y+=dy}
 next(bot){const a=this.cell(bot.x,bot.y),goal=this.cell(this.p.x,this.p.y),queue=[{...a,path:[]}],seen=new Set([a.x+','+a.y]);while(queue.length){const q=queue.shift();if(q.x===goal.x&&q.y===goal.y)return q.path[0];for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=q.x+dx,y=q.y+dy,key=x+','+y;if(this.map[y]?.[x]==='0'&&!seen.has(key)){seen.add(key);queue.push({x,y,path:[...q.path,{x:.08+(x+.5)*.06,y:.22+(y+.5)*.073}]})}}}return null}
 update(dt,i){this.tick(dt);if(this.done)return;const d=i.dir,m=Math.hypot(d.x,d.y)||1;if(m>.2&&(Math.abs(d.x)+Math.abs(d.y)>.2)){this.move(this.p,d.x/m*dt*.14*this.ch.speed,d.y/m*dt*.24*this.ch.speed);this.face=Math.atan2(d.y*H,d.x*W);this.still=0}else this.still+=dt;if(this.still>3.5&&this.bots.length<7){this.still=0;this.bots.push(this.bot(7,7))}for(const p of this.pages)if(!p.got&&(p.k!==2||this.alephVisible)&&Math.hypot((p.x-this.p.x)*1.77,p.y-this.p.y)<.044*this.ch.reach){p.got=true;this.got++;this.collect(p.x,p.y,200)}this.aiTime-=dt;if(this.aiTime<=0){this.aiTime=.3;for(const b of this.bots)if(!b.target)b.target=this.next(b)}for(const b of this.bots){if(b.target){const dx=b.target.x-b.x,dy=b.target.y-b.y,dist=Math.hypot(dx,dy);if(dist<.006){b.x=b.target.x;b.y=b.target.y;b.target=null}else{const step=Math.min(dist,dt*(.039+this.t*.0002));b.x+=dx/dist*step;b.y+=dy/dist*step}}if(Math.hypot((b.x-this.p.x)*1.77,b.y-this.p.y)<.047)this.hit()}if(this.got>=this.e.config.pageCount)this.finish();else if(this.t>=this.max){this.done=true;this.cleared=false}}
 get alephVisible(){return this.t%4<3}
 get alephOpacity(){const phase=this.t%4;return phase<.25?phase/.25:phase<2.75?1:phase<3?(3-phase)/.25:0}
 render(c){for(let y=0;y<9;y++)for(let x=0;x<15;x++)if(this.map[y][x]==='1'){rect(c,.08+x*.06,.22+y*.073,.059,.071,'#473845');rect(c,.08+x*.06,.22+y*.073,.059,.005,'#977663')}for(const p of this.pages)if(!p.got)letterPage(c,this.e.images['letter'+p.k],p.x,p.y,.027,p.k===2?this.alephOpacity:1);for(const b of this.bots)asset(c,this.e.images.eye,b.x,b.y,.043,.043);this.player(c,.08);c.save();const px=this.p.x*W,py=(this.p.y-.025)*H;const g=c.createRadialGradient(px,py,45,px,py,300);g.addColorStop(0,'#04030b00');g.addColorStop(.6,'#04030b60');g.addColorStop(1,'#04030beb');c.fillStyle=g;c.fillRect(0,0,W,H);c.globalCompositeOperation='screen';c.fillStyle='#fff1b70b';c.beginPath();c.moveTo(px,py);c.arc(px,py,290,this.face-.55,this.face+.55);c.closePath();c.fill();c.restore();this.effects(c)}get progress(){return this.got+' / 8 LETTERE'}
}
