export class InputManager {
 constructor(stage,action,onMode){this.enabled=false;this.stage=stage;this.keys=new Set();this.dir={x:0,y:0};this.action=false;this.justPressed=false;this.justReleased=false;this.idleTime=0;this.mode='keyboard';this.onMode=onMode;this.stick=null;this.actionId=null;this.touchAction=false;this.lastAction=false;this.jumpBuffer=0;this.lastDir='';this.movePressed='';this.joy=document.querySelector('#joystick');
 window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if(this.enabled&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();this.keys.add(e.code);this.setMode('keyboard')});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>this.clear());
 stage.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'||!this.enabled)return;this.setMode('touch');if(e.target.closest('#screen,.hud-right'))return;const r=stage.getBoundingClientRect();if(e.target===action){this.actionId=e.pointerId;this.touchAction=true;action.setPointerCapture(e.pointerId)}else if(e.clientX<r.left+r.width*.55&&!this.stick){this.stick={id:e.pointerId,x:e.clientX,y:e.clientY,dx:0,dy:0};stage.setPointerCapture(e.pointerId);this.joy.style.cssText=`display:block;left:${e.clientX-r.left-60}px;top:${e.clientY-r.top-60}px`;}e.preventDefault()});
 stage.addEventListener('pointermove',e=>{if(this.stick?.id!==e.pointerId)return;const s=this.stick,dx=e.clientX-s.x,dy=e.clientY-s.y,m=Math.hypot(dx,dy),k=Math.min(1,60/(m||1));s.dx=m<12?0:dx*k/60;s.dy=m<12?0:dy*k/60;this.joy.firstElementChild.style.transform=`translate(${dx*k}px,${dy*k}px)`;e.preventDefault()});
 const end=e=>{if(this.stick?.id===e.pointerId){this.stick=null;this.joy.style.display='none'}if(this.actionId===e.pointerId){this.actionId=null;this.touchAction=false}};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end);
 }
 setMode(v){if(this.mode!==v){this.mode=v;this.onMode(v)}}
 clear(){this.keys.clear();this.stick=null;this.touchAction=false;this.actionId=null;this.joy.style.display='none';this.dir={x:0,y:0};this.lastAction=false;this.lastDir='';this.jumpBuffer=0}
 update(dt){const k=this.keys;let x=Number(k.has('ArrowRight')||k.has('KeyD'))-Number(k.has('ArrowLeft')||k.has('KeyA')),y=Number(k.has('ArrowDown')||k.has('KeyS'))-Number(k.has('ArrowUp')||k.has('KeyW'));let action=k.has('Space')||this.touchAction;if(this.stick){x=this.stick.dx;y=this.stick.dy}const pad=Array.from(navigator.getGamepads?.()||[]).find(Boolean);if(pad){const px=pad.axes[0]||0,py=pad.axes[1]||0;if(Math.abs(px)>.2||Math.abs(py)>.2){x=px;y=py;this.setMode('keyboard')}x+=(pad.buttons[15]?.pressed?1:0)-(pad.buttons[14]?.pressed?1:0);y+=(pad.buttons[13]?.pressed?1:0)-(pad.buttons[12]?.pressed?1:0);action ||= !!pad.buttons[0]?.pressed;}this.dir={x:Math.max(-1,Math.min(1,x)),y:Math.max(-1,Math.min(1,y))};this.action=action;this.justPressed=action&&!this.lastAction;this.justReleased=!action&&this.lastAction;this.lastAction=action;this.jumpBuffer=this.justPressed?.12:Math.max(0,this.jumpBuffer-dt);const direction=Math.abs(x)>.3?(x<0?'left':'right'):y<-.3?'up':y>.3?'down':'';this.movePressed=direction&&direction!==this.lastDir?direction:'';this.lastDir=direction;this.idleTime=direction||action?0:this.idleTime+dt;}
 consumeJump(){this.jumpBuffer=0}
}
